export const REDIRECT_URI = 'http://localhost:3000/search'
export const AUTH_STATE_KEY = 'authState'
export const SCOPE = 'user-read-private user-read-email playlist-modify-public playlist-modify-private'
export const AUTHORIZE_URL = 'https://accounts.spotify.com/authorize'
export const ENTER = 'Enter'